#!/bin/sh
bladdons=/home/trickey/ltrickey/blender/2.57/scripts/addons
bliov=$bladdons/io_vector
cp vec/io_vector__init__.py $bliov/__init__.py
for f in geom.py model.py pdf.py triquad.py vecfile.py art2polyarea.py offset.py svg.py; do
  cp vec/$f $bliov
done
blmi=$bladdons/mesh_inset
cp vec/mesh_inset__init__.py $blmi/__init__.py
for f in geom.py model.py pdf.py triquad.py vecfile.py art2polyarea.py offset.py svg.py; do
  cp vec/$f $blmi
done
